---
version: "3.7"
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:3.10.2-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672